server:
  port: 0
spring:
  application:
    name: store-customer
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/poo
    # url: jdbc:mysql://127.0.0.1:3306/poo
    username: postgres
    password: Post123321
    driver-class-name: org.postgresql.Driver
    # driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}