server:
  port: 0

spring:
  application:
    name: store-customer
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://127.0.0.1:5432/poo}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:Post123321}
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}